---
- hosts: all
  become: yes
  tasks:
    - include: ./ansible/default_setting.yml
    - include: ./ansible/git_setting.yml
    - include: ./ansible/rbenv_setting.yml
    - include: ./ansible/node_setting.yml
