# for memcached setting
- block:
  - name: Install package memcached
    yum:
      name: http://rpms.remirepo.net/enterprise/6/remi/x86_64//memcached-1.5.16-1.el6.remi.x86_64.rpm
  - name: Run memcached service
    service:
      name: memcached
      state: started
      enabled: yes
